export const WEBHOOK_URL_STAGING = process.env.WEBHOOK_URL_STAGING;
export const WEBHOOK_SECRET_STAGING = process.env.WEBHOOK_SECRET_STAGING;

export const WEBHOOK_URL_PRODUCTION = process.env.WEBHOOK_URL_PRODUCTION;
export const WEBHOOK_SECRET_PRODUCTION = process.env.WEBHOOK_SECRET_PRODUCTION;